server:
  port: 8084

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=ajdbase;encrypt=false
    username: sa
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:com/example/dao/*Dao/*.xml
  type-aliases-package: com.example.pojo
  configuration:
    cache-enabled: true